export const INGREDIENTS_REQUEST: "INGREDIENTS_REQUEST" = "INGREDIENTS_REQUEST";
export const INGREDIENTS_SUCCESS: "INGREDIENTS_SUCCESS" = "INGREDIENTS_SUCCESS";
export const INGREDIENTS_FAILED: "INGREDIENTS_FAILED" = "INGREDIENTS_FAILED";
